application: anunaadam
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: images

- url: /documents
  static_dir: documents

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /(.+?)
  script: \1.php

- url: /
  script: main.php
